# docker-compose.yml

version: '3.8'

services:
  # --- 我们的 Go 后端服务 ---
#  smart-school-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080" # 将主机的 8080 端口映射到容器的 8080 端口
#    volumes:
#    # 如果需要，可以将本地代码挂载到容器中，方便开发时热更新
#      - .:/app
#    depends_on:
#      - db # 保证数据库容器先于我们的应用启动
#    environment:
#      # 我们可以在这里覆盖配置文件中的某些值，例如数据库地址
#      # 这使得我们的应用在不同环境（开发、生产）中更具灵活性
#      - DB_HOST=db
#    container_name: smart-school-api

  # --- MySQL 数据库服务 ---
  db:
    image: mysql:8.0 # 使用官方的 MySQL 8.0 镜像
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # 设置 root 用户的密码
      MYSQL_DATABASE: smart_school_db # 自动创建一个名为 smart_school_db 的数据库
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # 将主机的 3306 端口映射到容器的 3306 端口
    volumes:
      - mysql_data:/var/lib/mysql # 将数据库数据持久化，防止容器重启后数据丢失
    container_name: smart-school-db

  redis:
    image: redis:6.2-alpine # 使用官方的 Redis 镜像
    restart: always
    ports:
      - "6379:6379" # 将主机的 6379 端口映射到容器的 6379 端口
    container_name: smart-school-redis

volumes:
  mysql_data: