# 数据库配置
database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 2001928gsyhhh
  dbname: smart_school
  charset: utf8mb4
  parseTime: true
  loc: Local

# 服务器配置
server:
  port: 8080
  mode: debug  # debug, release, test

# JWT配置
jwt:
  secret: smart_school_secret_key
  expire: 24h  # 过期时间

# AI对话配置
ai:
  coze:
    url: "https://api.coze.cn/v1/workflow/stream_run"
    token: "pat_V3WKHNJjN4XeXGHWLjQUV9nz2qZI3dIcdgVIIbs1WqbDDUoJEWNnC7UY6um2cr0h"
    workflow_id: "7502453464644337698"